import { montserrat, roboto } from "@/helpers/fonts";
import "../global.scss";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"   className={`${roboto.variable} ${montserrat.variable}`}>
      <body>{children}</body>
    </html>
  );
}



